<table class="form">  <tr>    <th>{{mb_label object=$examen field="catalogue_labo_id"}}</th>    <td>      <select name="catalogue_labo_id">        {{foreach from=$listCatalogues item="curr_catalogue"}}        <option value="{{$curr_catalogue->_id}}" {{if $curr_catalogue->_id == $examen->catalogue_labo_id}}selected="selected"{{/if}}>          {{$curr_catalogue->_view}}        </option>        {{foreach from=$curr_catalogue->_ref_catalogues_labo item="curr_sub_catalogue"}}        <option value="{{$curr_sub_catalogue->_id}}" {{if $curr_sub_catalogue->_id == $examen->catalogue_labo_id}}selected="selected"{{/if}}>          &mdash; {{$curr_sub_catalogue->_view}}        </option>        {{/foreach}}        {{/foreach}}      </select>    </td>  </tr>
  <tr>    <th>{{mb_label object=$examen field="identifiant"}}</th>    <td>{{mb_field object=$examen field="identifiant"}}</td>  </tr>
  <tr>    <th>{{mb_label object=$examen field="libelle"}}</th>    <td>{{mb_field object=$examen field="libelle"}}</td>  </tr>
  <tr>    <th>{{mb_label object=$examen field="type"}}</th>    <td>{{mb_field object=$examen field="type"}}</td>  </tr>
  <tr>    <th>{{mb_label object=$examen field="unite"}}</th>    <td>{{mb_field object=$examen field="unite"}}</td>  </tr>
  <tr>    <th>{{mb_label object=$examen field="min"}}</th>    <td>{{mb_field object=$examen field="min"}}</td>  </tr>
  <tr>    <th>{{mb_label object=$examen field="max"}}</th>    <td>{{mb_field object=$examen field="max"}}</td>  </tr>
  <tr>    <th>{{mb_label object=$examen field="deb_application"}}</th>    <td class="date">{{mb_field object=$examen field="deb_application" form="editExamen"}}</td>  </tr>
  <tr>    <th>{{mb_label object=$examen field="fin_application"}}</th>    <td class="date">{{mb_field object=$examen field="fin_application" form="editExamen"}}</td>  </tr>
  <tr>    <th>{{mb_label object=$examen field="realisateur"}}</th>    <td>      <select name="realisateur">        <option value="">&mdash; Choisir une réalisateur</option>        {{foreach from=$groups item="_group"}}        <optgroup class="group" label="{{$_group->_view}}">        </optgroup>          {{foreach from=$_group->_ref_functions item="_function"}}          <optgroup label="{{$_function->_view}}">            {{foreach from=$_function->_ref_users item="_user"}}            <option class="mediuser" style="border-color: #{{$_function->color}};" value="{{$_user->_id}}">              {{$_user->_view}}            </option>            {{/foreach}}          </optgroup>          {{/foreach}}        {{/foreach}}      </select>
    </td>  </tr>  </table>
