<table class="form">  <tr>    <th>{{mb_label object=$examen field="catalogue_labo_id"}}</th>    <td>      <select name="catalogue_labo_id">        {{assign var="selected_id" value=$examen->catalogue_labo_id}}        {{assign var="exclude_id" value=""}}        {{foreach from=$listCatalogues item="_catalogue"}}
          {{if !$_catalogue->_locked || $examen->_locked}}            {{include file="options_catalogues.tpl"}}          {{/if}}
        {{/foreach}}      </select>    </td>  </tr>
  <tr>    <th>{{mb_label object=$examen field="identifiant"}}</th>    <td>{{mb_field object=$examen field="identifiant"}}</td>  </tr>
  <tr>    <th>{{mb_label object=$examen field="libelle"}}</th>    <td>{{mb_field object=$examen field="libelle"}}</td>  </tr>
  <tr>    <th>{{mb_label object=$examen field="type"}}</th>    <td>{{mb_field object=$examen field="type"}}</td>  </tr>
  <tr>    <th>{{mb_label object=$examen field="unite"}}</th>    <td>{{mb_field object=$examen field="unite"}}</td>  </tr>
  <tr>    <th>{{mb_label object=$examen field="min"}}</th>    <td>{{mb_field object=$examen field="min"}}</td>  </tr>
  <tr>    <th>{{mb_label object=$examen field="max"}}</th>    <td>{{mb_field object=$examen field="max"}}</td>  </tr>
  <tr>    <th>{{mb_label object=$examen field="deb_application"}}</th>    <td class="date">{{mb_field object=$examen field="deb_application" form="editExamen" register=true}}</td>  </tr>
  <tr>    <th>{{mb_label object=$examen field="fin_application"}}</th>    <td class="date">{{mb_field object=$examen field="fin_application" form="editExamen" register=true}}</td>  </tr>
  <tr>    <th>{{mb_label object=$examen field="realisateur"}}</th>    <td>      <select name="realisateur">        <option value="">&mdash; Choisir une réalisateur</option>        {{foreach from=$groups item="_group"}}        <optgroup class="group" label="{{$_group->_view}}">          <option class="novalue">{{tr}}NoValue{{/tr}}</option>        </optgroup>        {{foreach from=$_group->_ref_functions item="_function"}}        <optgroup label="{{$_function->_view}}">          {{foreach from=$_function->_ref_users item="_user"}}          <option class="mediuser" {{if $_user->_id == $examen->realisateur}}selected="selected"{{/if}}style="border-color: #{{$_function->color}};" value="{{$_user->_id}}">            {{$_user->_view}}          </option>          {{foreachelse}}          <option class="novalue">{{tr}}NoValue{{/tr}}</option>          {{/foreach}}        </optgroup>        {{/foreach}}        {{/foreach}}      </select>
    </td>  </tr>  </table>
